.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. ez25coin_qt test_ez25coin_qt
clean: FORCE
	$(MAKE) -C .. ez25coin_qt_clean test_ez25coin_qt_clean
check: FORCE
	$(MAKE) -C .. test_ez25coin_qt_check
ez25coin-qt ez25coin-qt.exe: FORCE
	 $(MAKE) -C .. ez25coin_qt
